const contactActionTypes = {
  FETCH_CONTACT_START: 'FETCH_CONTACT_START',
  FETCH_CONTACT_SUCCESS: 'FETCH_CONTACT_SUCCESS',
  FETCH_CONTACT_FAIL: 'FETCH_CONTACT_FAIL',

  POST_NEW_CONTACT_START: 'POST_NEW_CONTACT_START',
  POST_NEW_CONTACT_SUCCESS: 'POST_NEW_CONTACT_SUCCESS',
  POST_NEW_CONTACT_FAIL: 'POST_NEW_CONTACT_FAIL',

  FETCH_BY_ID_CONTACT_START: 'FETCH_BY_ID_CONTACT_START',
  FETCH_BY_ID_CONTACT_SUCCESS: 'FETCH_BY_ID_CONTACT_SUCCESS',
  FETCH_BY_ID_CONTACT_FAIL: 'FETCH_BY_ID_CONTACT_FAIL',

  DELETE_CONTACT_START: 'DELETE_CONTACT_START',
  DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',
  DELETE_CONTACT_FAIL: 'DELETE_CONTACT_FAIL',

  EDIT_CONTACT_START: 'EDIT_CONTACT_START',
  EDIT_CONTACT_SUCCESS: 'EDIT_CONTACT_SUCCESS',
  EDIT_CONTACT_FAIL: 'EDIT_CONTACT_FAIL',
};

export default contactActionTypes;
